version: 2.1
orbs:
    # The Python orb contains pre-packaged CircleCI configurations for Python projects.
    python: circleci/python@2.1.1

# Define the jobs we want to run.
jobs:
    run-unit-tests:
    # Specify the execution environment. We'll use a standard Python 3.10 image.
    docker:
        - image: cimg/python:3.10.5
    
    # Define the steps to be executed in this job.
    steps:
        # Step 1: Get the code from your repository.
        - checkout

        # Step 2: Install Python dependencies.
        - python/install-packages:
            pkg-manager: pip
            # Tell the orb that our requirements file is inside the 'app/' directory.
            app-dir: ./app
    
        # Step 3: Run the tests using pytest.
        - run:
            name: Run Tests
            # This command tells pytest to look for tests in the 'tests/' directory.
            command: python -m pytest tests/

# Define the workflows that orchestrate the jobs.
workflows:
    build-and-test:
    # This workflow will only run when you push changes to the 'main' branch.
    when:
        git/branch: main
    
    # The list of jobs to run in this workflow.
    jobs:
        - run-unit-tests:
            context:
            # IMPORTANT: You'll need to create a context in CircleCI
            # if your tests require secret environment variables.
            # For now, our simple test doesn't, but this is good practice.
            - dl-ai-courses # Replace with your own context name if needed